### PR TITLE
Device tree for the ATMEL AT86RF233 IEEE802.15.4 Transceiver

### PR DESCRIPTION
**Pull request by taherrera**
Thoroughly tested on the BeagleBone Black Rev C. Kernel version: Linux beaglebone 4.14.71-ti-r80

### CODE REVIEW

**Comment by RobertCNelson** [comment]
and merged! thanks @taherrera , sorry for the delay been traveling this last week..

**Comment by RobertCNelson** [comment]
and synced out to apt repo as: bb-cape-overlays_4.4.20190812.0

I made two small changes to fit in the cape-universal default rules we have setup:

https://github.com/beagleboard/bb.org-overlays/commit/194d2bbfcd867f10edcb8d303343e86b3c90d34c

https://github.com/beagleboard/bb.org-overlays/commit/409c99fcecc19e2cebfe39cae18e51c2603b7b3f

Shouldn't make any functional changes, to your version..

Regards,

**Comment by taherrera** [comment]
My pleasure Robert, I've got more capes for IEEE802.15.4 transceivers I would like to add to the repo, where can I get more info on these "default rules" ?

**Comment by RobertCNelson** [comment]
@taherrera so today, all overlays should have these default:

```
fragment@0 {
```

```
	/*
	 * Helper to show loaded overlays under: /proc/device-tree/chosen/overlays/
	 */
	fragment@0 {
		target-path="/";
		__overlay__ {

			chosen {
				overlays {
					BB-SPI0-AT86RF233-00A0 = __TIMESTAMP__;
				};
			};
		};
	};
```

This shows up in user-space, so we know what loaded with-out a serial usb debugger:

```
debian@beaglebone-xbee:~$ ls -lh /proc/device-tree/chosen/overlays/
total 0
-r--r--r-- 1 root root 25 Aug 12 16:22 BB-ADC-00A0
-r--r--r-- 1 root root 25 Aug 12 16:22 BB-BONE-eMMC1-01-00A0
-r--r--r-- 1 root root 25 Aug 12 16:22 M-BB-BBG-00A0
-r--r--r-- 1 root root  9 Aug 12 16:22 name
```

The second default is

```
fragment@1 {
```
With the move to "cape-univeral" defaulted-on from u-boot, all pin's are muxed, so we need to remove pins we want to use inthe overlay..

```
	fragment@2 {
		reg = <0>;
		target = <&am33xx_pinmux>;
		__overlay__ {
			bb_at86_pins: bb_at86_pins {
				pinctrl-single,pins = <
					0x040 0x27  /* irq | P9.15 gpio1[16] | MODE7 | INPUT | PULLDOWN */
					0x078 0x07  /* rst | P9.12 gpio1[28] | MODE7 | OUTPUT | PULLDOWN */
					0x044 0x07  /* slp | P9.23 gpio1[17] | MODE7 | OUTPUT | PULLDOWN */
				>;
			};
			spi0_at86_s0: spi0_at86_s0 {
				pinctrl-single,pins = <
					0x150 0x30  /* spi0_sclk, INPUT_PULLUP | MODE0 */
					0x154 0x30  /* spi0_d0, INPUT_PULLUP | MODE0 */
					0x158 0x10  /* spi0_d1, OUTPUT_PULLUP | MODE0 */
					0x15c 0x10  /* spi0_cs0, OUTPUT_PULLUP | MODE0 */
				>;
			};
		};
	};
```

This allows end users to still utilize config-pin for any pins still available in userspace.

Regards,

**Pull request merged**
