### PR TITLE
add omit_interrupt to tieqep.c devicetree overlays, show frequency example in bbone_eqep1

### PR DESCRIPTION
**Pull request by liftoff-sr**

### CODE REVIEW

**Comment by RobertCNelson** [comment]
What dtc compiler are you using?

```
-/dts-v1/;
-/plugin/;
+/dts-v1/ /plugin/;
```
This breaks the patched dtc compiler we ship in the repo...

```
voodoo@hades:/opt/github/bb.org/bb.org-overlays$ make
  DTC     src/arm/BB-UART5-00A0.dtbo
Error: src/arm/BB-UART5-00A0.dts:10.10-18 syntax error
FATAL ERROR: Unable to parse input tree
Makefile:134: recipe for target 'src/arm/BB-UART5-00A0.dtbo' failed
make[1]: *** [src/arm/BB-UART5-00A0.dtbo] Error 1
Makefile:82: recipe for target 'all_arm' failed
make: *** [all_arm] Error 2
voodoo@hades:/opt/github/bb.org/bb.org-overlays$ cat Makefile | grep dtc
DTC ?= /usr/local/bin/dtc
dtc-tmp = $(subst $(comma),_,$(dot-target).dts.tmp)
dtc_cpp_flags  = -Wp,-MD,$(depfile).pre.tmp -nostdinc	\
quiet_cmd_dtc = DTC     $@
cmd_dtc = $(CPP) $(dtc_cpp_flags) -x assembler-with-cpp -o $(dtc-tmp) $< ; \
                -d $(depfile).dtc.tmp $(dtc-tmp) ; \
        cat $(depfile).pre.tmp $(depfile).dtc.tmp > $(depfile)
	$(call if_changed_dep,dtc)
voodoo@hades:/opt/github/bb.org/bb.org-overlays$ /usr/local/bin/dtc --version
Version: DTC 1.4.1-g326d1530
```

**Comment by RobertCNelson** [comment]
patches 1,2 & 5 pushed

**Comment by liftoff-sr** [comment]
Attached is my openembedded recipe.

It appears to be branch

    dt-overlays6


of this:

    http://github.com/pantoniou/dtc.git

with attached patch.

I haven't had any problems using this code.

Dick


SUMMARY = "Device Tree Compiler"
DESCRIPTION = "The Device Tree Compiler is a tool used to manipulate the Open-Firmware-like device tree used by PowerPC kernels."
SECTION = "bootloader"
LICENSE = "GPLv2 | BSD"
DEPENDS = "flex-native bison-native"


SRC_URI = "git://github.com/pantoniou/dtc.git;protocol=git;branch=dt-overlays6 \
            file://make_install.patch;striplevel=0 \
           "

EXTRA_OEMAKE='PREFIX="${prefix}" LIBDIR="${libdir}" DESTDIR="${D}"'

S = "${WORKDIR}/git"

do_install () {
    oe_runmake install
}

PACKAGES =+ "${PN}-misc"
FILES_${PN}-misc = "${bindir}/convert-dtsv0 ${bindir}/ftdump ${bindir}/dtdiff"



SRCREV = "4273dca28b716396cefde8027c7b3280a0b9a4b5"

require dtc.inc

PV = "1.4"

S = "${WORKDIR}/git"

BBCLASSEXTEND = "native nativesdk"


SRCREV = "4273dca28b716396cefde8027c7b3280a0b9a4b5"

require dtc.inc

PV = "1.4"

inherit native

NATIVE_INSTALL_WORKS = "1"

do_install() {
        install -d ${D}${bindir}
        install -m 755 dtc ${D}${bindir}/
}

**Comment by RobertCNelson** [comment]
Odd we are still on "dt-overlays5"

dt-overlay6 actually looks broken:

dt-overlay5:
https://github.com/pantoniou/dtc/commit/dac84271d5bd96117fa2b35975f57c05168b7c6c

```
 sourcefile:
-	  DT_V1 ';' memreserves devicetree
+	  DT_V1 ';' plugindecl memreserves devicetree
 		{
-			the_boot_info = build_boot_info($3, $4,
-							guess_boot_cpuid($4));
+			$5->is_plugin = $3;
+			the_boot_info = build_boot_info($4, $5,
+							guess_boot_cpuid($5));
+		}
+	;
+
+plugindecl:
+	/* empty */
+		{
+			$$ = false;
+		}
+	| DT_PLUGIN ';'
+		{
+			$$ = true;
```

dt-overlay6:
https://github.com/pantoniou/dtc/commit/17b9daa69434e1252389658af1326bc6757d4dfb

```
 sourcefile:
-	  DT_V1 ';' memreserves devicetree
+	    basesource
+	  | pluginsource
+	  ;
+
+basesource:
+	  DT_V1 ';' plugindecl memreserves devicetree
+		{
+			source_is_plugin = $3;
+			if (source_is_plugin)
+				deprecated_plugin_syntax_warning = true;
+			the_boot_info = build_boot_info($4, $5,
+							guess_boot_cpuid($5));
+		}
+	;
+
+plugindecl:
+	/* empty */
+		{
+			$$ = false;
+		}
+	| DT_PLUGIN ';'
+		{
+			$$ = true;
+		}
+	;
+
```

adding @pantoniou

**Comment by liftoff-sr** [comment]
I can use any single DTC source tree in an openembedded recipe, but the double dipping
done in your dtc build script is difficult in an openembedded recipe.

Its also a questionable strategy even for a shell script in terms of sane software
maintenance.

The bone community should be able to have a single DTC source tree, this is a pretty basic
and commonly expected ask of something that is bone specific and fairly stable.

In that single tree merging can be done, rather than doing it on the fly in a build recipe.

Let me know what single tree you recommend please.

Dick

**Comment by RobertCNelson** [comment]
@liftoff-sr just pushed:

https://github.com/RobertCNelson/dtc/tree/bb.org-4.1-dt-overlays5

yes i should have done that sooner. ;)

**Comment by RobertCNelson** [comment]
For Everyone's future reference:

dtc: 3.8.x kernel: https://github.com/RobertCNelson/dtc/tree/bb.org-3.8
dtc: 4.1.x -> 4.4.x(head) kernel: https://github.com/RobertCNelson/dtc/tree/bb.org-4.1-dt-overlays5

I pray, the mainline version of dtc ends up close to bb.org-4.1-dt-overlays5

Regards,

**Comment by liftoff-sr** [comment]
> I pray, the mainline version of dtc ends up close to bb.org-4.1-dt-overlays5

The beauty of open source is that folks with different opinions can go their own separate
way, with the only cost being an increase in maintenance work.

DTC is not such a big program that this is an issue.  A future compromise might mean folks
will have to change their DTC compiler overnight to use adapted overlays, but even this is
not a tragedy.

IMO opinion the binary format of the overlays is the real enabler.  The source code for it
and the compiler could morph through significantly different evolutionary paths.

The mainline kernel developers are difficult to work with IMO, so one should not have high
expectations on reaching agreement.  This leaves the door open to a pleasant surprise, as
well as a superior implementation on the part of the bone community.

**Comment by liftoff-sr** [comment]
> The mainline kernel developers are difficult to work with IMO, so one should not have high
> expectations on reaching agreement.  This leaves the door open to a pleasant surprise, as
> well as a superior implementation on the part of the bone community.

If I was doing with a blank slate, I would not even have chosen C as the implementation
language.  After all, why program on your hands and knees in userspace?

Out, thanks for the tree pointer.

**Pull request closed without merging**
