### PR TITLE
add MCP2515 overlay by Mark K Cowan

### PR DESCRIPTION
**Pull request by pdp7**
From https://github.com/battlesnake/beaglebone-spi0-mcp2515/blob/master/MCP2515.dts
by Mark K Cowan

GitHub gist:
https://gist.github.com/pdp7/20dddbeffe83082e3c94ab0903563783

Wire the MCP2515 to SPI0 on the BeagleBone Black:
https://photos.app.goo.gl/1UUAHhRngzwiVWha9

add this to /boot/uEnv.txt:
uboot_overlay_addr0=/lib/firmware/BB-SPIDEV0-00A0.dtbo
uboot_overlay_addr1=/lib/firmware/MCP2515.dtbo

### CODE REVIEW

**Comment by pdp7** [comment]
thanks to @battlesnake for creating this .dts

@RobertCNelson does this look ok?

I have tested it with hardware.

**Comment by battlesnake** [comment]
My work is MIT-licensed.  I couldn't see any license info in this repository from a quick glance, but you should be fine incorporating my stuff.  If there's any issue, let me know and I'll re-license it.

**Comment by RobertCNelson** [comment]
@pdp7 @battlesnake sorry for the delay! Holiday distractions. :)

MIT is fine, i'd prefer we could dual license all the older gpl *.dts options, but they are from the 3.8.x days of CircuitCo, so hard to get relicensed..

Regards,

**Comment by pdp7** [comment]
@battlesnake is it possible to dual license as MIT and GPL (based on @RobertCNelson comment)?
thanks!

**Comment by RobertCNelson** [comment]
@pdp7, i wouldn't worry about that, having MIT on new submissions is the directions i'd like to see ;)

**Pull request merged**
