### PR TITLE
add BB-UART2-00A1.dts

### PR DESCRIPTION
**Pull request by Pillar1989**
If someone wants to use beaglebone green gateway's grove uart interface, this dts will be very helpful

### CODE REVIEW

**Comment by RobertCNelson** [comment]
@Pillar1989 thanks i merged this in, but these don't conflict with any headers pins, we should just enable them by default..

Regards,

**Comment by RobertCNelson** [comment]
https://github.com/beagleboard/BeagleBoard-DeviceTrees/commit/fb6664451510919e13b089588c8e419125369f19

**Comment by jadonk** [comment]
Why does this look like it is in the wrong directory?

**Comment by RobertCNelson** [comment]
@jadonk because it is! ugh.

**Pull request merged**
