### PR TITLE
BBB Load Cape overlay

### PR DESCRIPTION
**Pull request by lorforlinux**
@RobertCNelson please review my code :) 
I don't know why the indentation looks off here, it looks good on the local machine. 
Also, I wanted to ask you if you have ever used the LCD7/LCD4 Cape with BBB/BBAI, If yes can you let me know the process?

### CODE REVIEW

**Comment by RobertCNelson** [comment]
@lorforlinux so i got two lcd's working (never touched the key buttons)

https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BBAI_BB-BONE-LCD7-01-00A2.dts

https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BBAI_BB-BONE-LCD7-01-00A3.dts

Regards,

**Comment by lorforlinux** [comment]
Thanks, that's very helpful :)
Do you know what makes the indentation go crazy?

**Comment by RobertCNelson** [comment]
I'm not sure, i wouldn't worry about it too much, at some point we are going to convert to dtc's newer syntax as shown here:

https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BBORG_GAMEPUP-00A2.dts

So all formatting will be redone ;)

**Comment by lorforlinux** [comment]
Should I use this format for new DT files? As I will be submitting a lot of pull requests ;)

**Comment by RobertCNelson** [comment]
Only if you want too, i haven't done a good job to convert our existing ones to the new syntax..

**Comment by RobertCNelson** [comment]
I'm pretty sure both the backlight and touchscreen worked...  I think it was with v4.14.x-ti (might have even been v4.9.x-ti) kernel's..

Did the index numbers change on us again?

The repo assumes v4.14.x+

**Comment by lorforlinux** [comment]
> Did the index numbers change on us again?

I confirmed the index on interface spec page and BBAI SRM
https://elinux.org/Beagleboard:BeagleBone_cape_interface_spec#PWM.2FTIMER.2FECAP
https://github.com/beagleboard/beaglebone-ai/wiki/System-Reference-Manual#p9.14-p9.16

>I'm pretty sure both the backlight and touchscreen worked... I think it was with v4.14.x-ti (might have even been v4.9.x-ti) kernel's..

I am not able to understand why is i2c1 is a target :(

> The repo assumes v4.14.x+

I have not tested the overlay yet, don't have the hardware in hand.

**Pull request merged**
